name: Sync To Gitee

on: [push, delete, create]

jobs:

  sync:
  
    runs-on: ubuntu-latest

    steps:

      # Runs a single command using the runners shell
      - name: Sync To Gitee
        run: echo Hello, world!
